module:
  admin_denied: 0
  big_pipe: 0
  block: 0
  breakpoint: 0
  ckeditor: 0
  components: 0
  config: 0
  csv_serialization: 0
  ctools: 0
  custom_widgets: 0
  datetime: 0
  datetime_range: 0
  dream_block_manager: 0
  dynamic_page_cache: 0
  editor: 0
  external_entities: 0
  external_media: 0
  facets: 0
  facets_pretty_paths: 0
  facets_rest: 0
  facets_summary: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  flysystem: 0
  geofield: 0
  help: 0
  image: 0
  inline_entity_form: 0
  language: 0
  leaflet: 0
  leaflet_markercluster: 0
  leaflet_views: 0
  link: 0
  maintenance200: 0
  media: 0
  media_library: 0
  menu_ui: 0
  node: 0
  node_title_help_text: 0
  ocha_assessment_document: 0
  ocha_assessments: 0
  ocha_countries: 0
  ocha_disasters: 0
  ocha_docstore_files: 0
  ocha_global_coordination_groups: 0
  ocha_hid_contacts: 0
  ocha_integrations: 0
  ocha_knowledge_management: 0
  ocha_local_groups: 0
  ocha_locations: 0
  ocha_map: 0
  ocha_organizations: 0
  ocha_persons: 0
  ocha_population_type: 0
  ocha_themes: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  pcb: 0
  rdf: 0
  rest: 0
  search_api: 0
  search_api_db: 0
  search_api_solr: 0
  select2: 0
  select2_facets: 0
  serialization: 0
  shortcut: 0
  social_api: 0
  social_auth: 0
  social_auth_hid: 0
  syslog: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  user: 0
  views_data_export: 0
  views_ui: 0
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  common_design: 0
  common_design_subtheme: 0
  cd_seven: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
