session:
  parameter: language
url:
  source: path_prefix
  prefixes:
    en: ''
    fr: fr
    ru: ru
    es: es
    ar: ar
  domains:
    en: ''
    fr: ''
    ru: ''
    es: ''
    ar: ''
selected_langcode: site_default
_core:
  default_config_hash: uEePITI9tV6WqzmsTb7MfPCi5yPWXSxAN1xeLcYFQbM
